const faq = [
  {
    question: "What is Solve It! and what does it offer?",
    answer:
      "Solve It! is a dedicated website that provides solutions for a variety of mind-challenging puzzles. Our platform offers solvers for popular games such as Sudoku, Nonogram, Crosswords, and more.",
  },
  {
    question: "How does Solve It! work?",
    answer:
      "Solve It! utilizes advanced algorithms and solving techniques to provide accurate and efficient solutions to puzzles. Simply input the puzzle details, and our solvers will do the rest, guiding you to the solution.",
  },
  {
    question: "What types of puzzles does Solve It! support?",
    answer:
      "Solve It! currently supports a range of puzzles, including but not limited to Sudoku, Nonogram (Picross), Crosswords, and other popular logic-based games. We are continuously expanding our offerings to include more puzzle types.",
  },
  {
    question: "Is Solve It! free to use?",
    answer:
      "Yes, Solve It! is completely free to use. Our mission is to make puzzle-solving accessible to everyone, and we are committed to keeping our services free of charge.",
  },
  {
    question: "Do I need to create an account to use Solve It!?",
    answer:
      "No account creation is required to use Solve It!. You can access our solvers and solve puzzles anonymously without the need for any sign-up process.",
  },
  {
    question: "Can Solve It! solve any difficulty level of puzzles?",
    answer:
      "Solve It! is designed to handle puzzles of varying difficulty levels. Whether you're a beginner or an expert, our solvers are equipped to tackle puzzles of different complexities.",
  },
  {
    question:
      "Are the solutions generated by Solve It! guaranteed to be correct?",
    answer:
      "While our solvers are highly accurate, the correctness of the solution ultimately depends on the accuracy of the input provided. We recommend double-checking your puzzle details to ensure accurate results.",
  },
  {
    question: "Can Solve It! be used on mobile devices?",
    answer:
      "Yes, Solve It! is optimized for mobile use. You can easily access our website and use the solvers on your smartphone or tablet, making it convenient to solve puzzles on the go.",
  },
  {
    question:
      "Does Solve It! have a community or forums for puzzle enthusiasts?",
    answer:
      "Currently, Solve It! focuses on providing efficient solvers. However, we are exploring options for community features in the future. Stay tuned for updates!",
  },
  {
    question: "How often are new puzzle types added to Solve It!?",
    answer:
      "We are actively working on expanding our selection of supported puzzles. New puzzle types and features are regularly added, so be sure to check back for updates.",
  },
];

/**
 *
 * @param {MouseEvent} e
 */

// The Function to toggle the FAQ Content
function toggleContent(e) {
  const content = e.currentTarget.faqContent;
  content.show = !content.show;

  content.style.height = content.show
    ? content.scrollHeight + 20 + `px`
    : `0px`;
  content.style.padding = content.show ? `10px 0` : `0`;

  const plus = e.currentTarget.plus;
  plus.style.transform = content.show ? `rotate(45deg)` : `none`;
}

// The Template Function for the FAQ
faq.forEach(function (item, index) {
  const faqItem = document.createElement(`div`);
  faqItem.classList.add(`faq`);
  faqItem.innerHTML = `
          <div class="faq_title">
              <span>${item.question}</span>
              <div class="plusBtn">
                <svg
                class="plus"
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="#ffb780"
                viewBox="0 0 16 16"
                stroke-width="2"
                stroke="#ffb780"
                >
                  <path
                    fill-rule="evenodd"
                    d="M8 0a.75.75 0 01.75.75v6.5h6.5a.75.75 0 010 1.5h-6.5v6.5a.75.75 0 01-1.5 0v-6.5H.75a.75.75 0 010-1.5h6.5V.75A.75.75 0 018 0z"
                  />
                </svg>
              <div>
          </div>
      `;

  faqItem.plus = faqItem.querySelector(`.plus`);

  const faqContent = document.createElement(`div`);
  faqContent.classList.add(`faq_content`);
  faqContent.innerHTML = item.answer;
  faqItem.appendChild(faqContent);

  faqItem.faqContent = faqContent;

  faqItem.addEventListener(`click`, toggleContent);
  document.querySelectorAll(`.faqs_container`)[index % 2].appendChild(faqItem);
});
